- !!org.example.Product
  name: Espresso Machine
  price: 1200
  suppliers:
  - &id001
    companyName: SupplyCo
- !!org.example.Product
  name: Coffee Grinder
  price: 150
  suppliers:
  - *id001
  - &id002
    companyName: GlobalGoods
- !!org.example.Product
  name: Milk Frother
  price: 50
  suppliers:
  - *id002
- !!org.example.Product
  name: Automatic Brewer
  price: 1800
  suppliers:
  - *id001
  - &id003
    companyName: MachineMart
- !!org.example.Product
  name: Water Filter
  price: 25
  suppliers:
  - *id003
